- name: add rabbitmq key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add rabbitmq repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install rabbitmq
  become: yes
  become_method: sudo
  apt: pkg=rabbitmq-server state=latest

- name: create /etc/rabbitmq
  become: yes
  become_method: sudo
  file: path=/etc/rabbitmq state=directory

- name: create rabbitmq config
  become: yes
  become_method: sudo
  template: src=rabbitmq.config.tpl dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq

- name: fetch delayed messages plugin
  become: yes
  become_method: sudo
  notify: restart rabbitmq
  get_url: url=http://www.rabbitmq.com/community-plugins/v3.6.x/rabbitmq_delayed_message_exchange-0.0.1.ez dest=/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.1/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez

- name: enable rabbit plugins
  notify: restart rabbitmq
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_delayed_message_exchange,rabbitmq_shovel,rabbitmq_shovel_management state=enabled
