- name: add rabbitmq key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add rabbitmq repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install rabbitmq
  sudo: yes
  apt: pkg=rabbitmq-server state=latest

- name: create /etc/rabbitmq
  sudo: yes
  file: path=/etc/rabbitmq state=directory

- name: create rabbitmq config
  sudo: yes
  template: src=rabbitmq.config.tpl dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq

- name: fetch delayed messages plugin
  sudo: yes
  notify: restart rabbitmq
  get_url: url=http://www.rabbitmq.com/community-plugins/v3.5.x/rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez dest=/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.4/plugins/rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez

- name: enable rabbit plugins
  notify: restart rabbitmq
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_delayed_message_exchange,rabbitmq_shovel,rabbitmq_shovel_management state=enabled
