- name: Install php5
  become: yes
  become_method: sudo
  apt: pkg=php5 state=latest

- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'
