- name: Install php5-cli
  become: yes
  become_method: sudo
  apt: pkg=php5-cli state=latest

- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'
